namespace PortailMediatheque.Api.Models;

// EF Core entity — FR34, FR35
// Column names follow EF default (PascalCase matches property name)
// NEVER hand-edit Migrations/ — generated by EF Core tools
public class Book
{
    public int Id { get; set; }
    public string Isbn { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Author { get; set; } = string.Empty;
    public string Genre { get; set; } = string.Empty;
    public int PublicationYear { get; set; }
    public string? CoverImageUrl { get; set; }
    public string? CuratorNote { get; set; }
    public DateTime DateAdded { get; set; } // FR35: auto-set in BookService.CreateAsync
    public bool IsSelectionDuMois { get; set; }
    public string Status { get; set; } = "available"; // FR26: forward-compat
}
